name: golpo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.4.0
  audioplayers: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  

  fonts:
    - family: asap
      fonts:
        - asset: fonts/asap/AsapCondensed-Regular.ttf
        - asset: fonts/asap/AsapCondensed-Bold.ttf
          weight: 700

  assets:
    - music/
    - music/bg/
    - music/bg/szbg1.ogg

